  # Base Configuration for tpRenamer Tool in Maya

# List of categories for renamer
categories:
  - objects:
      title: Objects
      icon: object
      types:
        - Transforms:
            type: transform
        - Shapes:
            type: shape
  - materials:
      title: Materials
      icon: material
      types:
        - Materials:
            fn: ls
            args:
              mat: True
        - Shaders:
            type: shadingEngine
  - layers:
      title: Layers
      icon: layer
      types:
        - Display Layers:
            type: displayLayer
  - cameras:
      title: Cameras
      icon: camera
      types:
        - Cameras:
            type: camera
  - lights:
      title: Lights
      icon: light
      types:
        - Lights:
            type: light
  - files:
      title: Files
      icon: file
      types: {}

# List of DCC nodes that should be discarded during renaming process
nodes_to_discard: ['persp', 'top', 'front', 'side', 'defaultLayer']

# List of DCC types that should be discarded during renaming process
types_to_discard: ['displayLayerManager', 'renderLayerManager', 'shapeEditorManager', 'poseInterpolatorManager', 'lightLinker']